name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon="icon.ico" --collect-all customtkinter "kanban_csv.py"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kanban-CSV-Executable
        path: dist/kanban_csv.exe
